export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

export const SHOW_NOTES_REQUEST = 'SHOW_NOTES_REQUEST';
export const SHOW_NOTES_SUCCESS = 'SHOW_NOTES_SUCCESS';
export const SHOW_NOTES_FAIL = 'SHOW_NOTES_FAIL';